### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

### ISSUE THREAD

**Issue by yswtrue** [ioridev/flutter_applovin_max#27]
```
E/AndroidRuntime( 6404): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 6404): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 6404): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 6404): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 6404): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6404): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 6404): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Sentry  ( 6404): Uncaught exception received.
```

**Comment by seemelala** [comment]
use 'com.applovin:applovin-sdk:10.3.5'
