### ISSUE TITLE
Errors when trying to load and display Ads 

### ISSUE THREAD

**Issue by defemz** [ioridev/flutter_applovin_max#36]
Hi everyone. Ia mtrying to load and display ads but after following all the steps in the documentation, no ads(test ads) is being shown in the emulator and the following message was displayed in the console:

```
Syncing files to device Android SDK built for x86...
D/EGL_emulation(10041): eglMakeCurrent: 0xdfd4eee0: ver 3 0 (tinfo 0xc7506600)
E/BufferQueueProducer(10041): [SurfaceTexture-0-10041-2] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(10041): [SurfaceTexture-0-10041-2] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(10041): [SurfaceTexture-0-10041-2] setAsyncMode: BufferQueue has been abandoned
Restarted application in 6,570ms.
D/FRCPlugin(10041): Sending fetchTimeout: 60
I/chatty  (10041): uid=10084(diamy.xxxxxx.formalournal) 1.ui identical 1 line
D/Banner Max Android(10041): Constructor
W/AppLovinSdk(10041): [AppLovinSdk] Attempted to load ad before SDK initialization. Please wait until after the SDK has initialized, e.g. AppLovinSdk.initializeSdk(Context, SdkInitializationListener).
D/EGL_emulation(10041): eglMakeCurrent: 0xdfd4eee0: ver 3 0 (tinfo 0xc7506600)
D/FRCPlugin(10041): Sending fetchTimeout: 60
I/flutter (10041): 
I/flutter (10041): 
I/flutter (10041): 6
D/AppLovinSdk(10041): [MaxInterstitialAd] Created new MaxInterstitialAd (MaxInterstitialAd{adUnitId='xxxxxxxxxxx', adListener=null, revenueListener=null, isReady=false})
W/AppLovinSdk(10041): [AppLovinSdk] Attempted to load ad before SDK initialization. Please wait until after the SDK has initialized, e.g. AppLovinSdk.initializeSdk(Context, SdkInitializationListener).
W/AppLovinSdk(10041): [MediationAdLoadManager] Attempting to load ad for same ad unit id (xxxxxxxxxx) while another ad load is already in progress!
D/Banner Max Android(10041): Constructor
W/AppLovinSdk(10041): [AppLovinSdk] Attempted to load ad before SDK initialization. Please wait until after the SDK has initialized, e.g. AppLovinSdk.initializeSdk(Context, SdkInitializationListener).
D/EGL_emulation(10041): eglMakeCurrent: 0xdfd4eee0: ver 3 0 (tinfo 0xc7506600)
E/BufferQueueProducer(10041): [SurfaceTexture-0-10041-3] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(10041): [SurfaceTexture-0-10041-3] setAsyncMode: BufferQueue has been abandoned
D/Banner Max Android(10041): Constructor
W/AppLovinSdk(10041): [AppLovinSdk] Attempted to load ad before SDK initialization. Please wait until after the SDK has initialized, e.g. AppLovinSdk.initializeSdk(Context, SdkInitializationListener).
D/EGL_emulation(10041): eglMakeCurrent: 0xdfd4eee0: ver 3 0 (tinfo 0xc7506600)
E/flutter (10041): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2215 pos 12: '!_debugDisposed': is not true.
E/flutter (10041): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
E/flutter (10041): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (10041): #2      RenderObject.markNeedsPaint (package:flutter/src/rendering/object.dart:2215:12)
E/flutter (10041): #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:199:5)
E/flutter (10041): <asynchronous suspension>
E/flutter (10041): 
```
I used the following code for banner and interstitial Ads respectively:
```
BannerMaxView((AppLovinAdListener event) =>
          print(event), BannerAdSize.banner, "yyyyyyyyyyyy");

isInterstitialVideoAvailable =
        await FlutterApplovinMax.isInterstitialLoaded(listener);
        if (isInterstitialVideoAvailable) {
          FlutterApplovinMax.showInterstitialVideo((AppLovinAdListener event) =>
              listener(event)).then((value) {
            FlutterApplovinMax.initInterstitialAd("xxxxxxxxxxx");
```

My question is why is this not working?

**Comment by afrimglobal** [comment]
You need to call the following in initState method: 
FlutterApplovinMax.initInterstitialAd("xxxxxxxxxxx");

but instead, you chose to call it last

**Comment by defemz** [comment]
> You need to call the following in initState method: FlutterApplovinMax.initInterstitialAd("xxxxxxxxxxx");
> 
> but instead, you chose to call it last

Thanks for you help. However, I did call the FlutterApplovinMax.initInterstitialAd("xxxxxxxxxxx"); in initState but ad was still not being displayed

**Comment by afrimglobal** [comment]
try my plugin version, there is an improvement, just add your ad unit ids
to the places where you see YOUR_AD_UNIT_ID for banner and rewarded video.
Then in your manifest  add your Applovin api_key to the value provided.
Cheers

**Comment by defemz** [comment]
Surprisingly when I updated applovin SDK to the latest version, ads started showing.
