### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to destroy MainActivity java.lang.NullPointerException

### ISSUE THREAD

**Issue by roma7481** [ioridev/flutter_applovin_max#50]
Getting this exception on Firebase crashlytics

Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void w7.k.e(w7.k$c)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5667)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5712)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
       
       
       
       
       
 flutter doctor                   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1268, on macOS 12.4 21F79 darwin-arm, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2019.3.5)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by thomasmso** [comment]
Hey there - AppLovin just released an official plugin. Please feel free to check it out here: ([docs](https://dash.applovin.com/documentation/mediation/flutter/getting-started/integration), [repo](https://github.com/AppLovin/AppLovin-MAX-Flutter)).

Thank you @ioridev for developing this stop-gap solution, we really appreciate it.
